### ISSUE TITLE
Add ssh2 & expect

### ISSUE THREAD

**Issue by jmsche** [shivammathur/homebrew-extensions#1097]
Hi there,

First, let met thank you as your repositories saved me a lot of time, being in Github Actions, or more recently on macOS :)

It would be nice to have the [ssh2](https://pecl.php.net/package/ssh2) and [expect](https://pecl.php.net/package/expect) extensions available :)

**Comment by shivammathur** [comment]
@jmsche Added in https://github.com/shivammathur/homebrew-extensions/commit/5b8c3816da246f74450a7d166273090b85c81197 and https://github.com/shivammathur/homebrew-extensions/commit/44b7b0b83b3e1a4de130c17a132993a85df2b4a0
