### ISSUE TITLE
Add the default version for easy upgrade

### ISSUE THREAD

**Issue by wtry** [shivammathur/homebrew-extensions#1300]
Correspond to the main version 
shivammathur/php/php

Can add one 
shivammathur/extensions/redis
shivammathur/extensions/mongodb

**Comment by shivammathur** [comment]
Added in https://github.com/shivammathur/homebrew-extensions/commit/3e4f26170a90bcaeacfd7c6aa9e3f58ef62bc5c7

**Comment by shivammathur** [comment]
I had to revert this as adding default aliases causes problems for extensions where the libraries they use have the same name as the extension for eg `expect` and `grpc`.

So please use the `extension@version` formula names.
