### ISSUE TITLE
memcached version for php 8+ is wrong

### ISSUE THREAD

**Issue by sschueller** [shivammathur/homebrew-extensions#1834]
**Describe the bug**
Symfony requires at least memcached php extension version 3.2.0 for php 8+ projects (https://github.com/symfony/symfony/blob/308652c1d7cbbc600b5b80186008fb8d63b38059/src/Symfony/Component/Cache/Adapter/MemcachedAdapter.php#L79). The memcached version here (https://github.com/shivammathur/homebrew-extensions/blob/master/Formula/memcached%408.0.rb#L13) for php8+ is still using version 3.1.5 but should be version 3.2.0 for php8+ https://pecl.php.net/package-changelog.php?package=memcached. Sury (packages.sury.org) for debian has memcached php extension version 3.2.0 for php 8+ as well.

**PHP versions**
8.0, 8.1, 8.2

**Comment by shivammathur** [comment]
@sschueller 

Upgraded `memcached` to 3.2.0 for PHP 7.0 and newer

**Comment by tft7000** [comment]
@shivammathur 
I tested memcached 3.2 with php 8.0 and php 8.1 locally on MacOs 12.4 (M1). I get the following errors on php startup:

with 8.1
```
 PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/homebrew/opt/memcached@8.1/memcached.so' (tried: /opt/homebrew/opt/memcached@8.1/memcached.so (dlopen(/opt/homebrew/opt/memcached@8.1/memcached.so, 0x0009): symbol not found in flat namespace '_php_msgpack_serialize'), /opt/homebrew/lib/php/pecl/20210902//opt/homebrew/opt/memcached@8.1/memcached.so.so (dlopen(/opt/homebrew/lib/php/pecl/20210902//opt/homebrew/opt/memcached@8.1/memcached.so.so, 0x0009): tried: '/opt/homebrew/lib/php/pecl/20210902//opt/homebrew/opt/memcached@8.1/memcached.so.so' (no such file))) in Unknown on line 0
```

with 8.0 similar:
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/homebrew/opt/memcached@8.0/memcached.so' (tried: /opt/homebrew/opt/memcached@8.0/memcached.so (dlopen(/opt/homebrew/opt/memcached@8.0/memcached.so, 0x0009): symbol not found in flat namespace '_php_msgpack_serialize'), /opt/homebrew/lib/php/pecl/20200930//opt/homebrew/opt/memcached@8.0/memcached.so.so (dlopen(/opt/homebrew/lib/php/pecl/20200930//opt/homebrew/opt/memcached@8.0/memcached.so.so, 0x0009): tried: '/opt/homebrew/lib/php/pecl/20200930//opt/homebrew/opt/memcached@8.0/memcached.so.so' (no such file))) in Unknown on line 0
```

Am I doing something wrong? do I need to install something in addition?

**Comment by baumannsven** [comment]
Apple M1
Homebrew 3.5.3

I have problem with memcached by php 7.1,7.2,7.3,7.4.

```bash
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/homebrew/opt/memcached@7.1/memcached.so' - dlopen(/opt/homebrew/opt/memcached@7.1/memcached.so, 0x0009): symbol not found in flat namespace '_php_msgpack_serialize' in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/opt/homebrew/opt/memcached@7.1/memcached.so' - dlopen(/opt/homebrew/opt/memcached@7.1/memcached.so, 0x0009): symbol not found in flat namespace '_php_msgpack_serialize' in Unknown on line 0
```

Other php versions works fine (5.6,8.0,8.1,8.2)

**Comment by tft7000** [comment]
@shivammathur : I can confirm that your fix together with the update/reinstall/rm worked for php 8.0 and php 8.1.
for both I needed to remove all three old config files: `rm msgpack.ini memcached.ini igbinary.ini`

thanks for your work!

**Comment by adampatterson** [comment]
I am experiencing the exact same error. 

Originally PHP 7.4, 8.0, and 8.1 were working.

I installed 8.2 and was not sure if something changed before or after but For 8.0 I had I fixed the error by looking at the loaded configs and saw that there was a `30-memcached.conf` and a `memcached.conf` deleting `memcached.conf` and one other file that I don't remember fixed the problem.

you should see another file `20-xxxxx.conf` delete the one without the `20-` this is to ensure proper load order.

unfortunately, this is not the case for PHP 8.1.

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/memcached@8.1/memcached.so' (tried: /usr/local/opt/memcached@8.1/memcached.so (dlopen(/usr/local/opt/memcached@8.1/memcached.so, 0x0009): symbol not found in flat namespace '_igbinary_serialize'), /usr/local/lib/php/pecl/20210902//usr/local/opt/memcached@8.1/memcached.so.so (dlopen(/usr/local/lib/php/pecl/20210902//usr/local/opt/memcached@8.1/memcached.so.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210902//usr/local/opt/memcached@8.1/memcached.so.so' (no such file))) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/memcached@8.1/memcached.so' (tried: /usr/local/opt/memcached@8.1/memcached.so (dlopen(/usr/local/opt/memcached@8.1/memcached.so, 0x0009): symbol not found in flat namespace '_igbinary_serialize'), /usr/local/lib/php/pecl/20210902//usr/local/opt/memcached@8.1/memcached.so.so (dlopen(/usr/local/lib/php/pecl/20210902//usr/local/opt/memcached@8.1/memcached.so.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210902//usr/local/opt/memcached@8.1/memcached.so.so' (no such file))) in Unknown on line 0
PHP 8.1.8 (cli) (built: Jul  8 2022 10:58:31) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.8, Copyright (c), by Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans
```

**Comment by adampatterson** [comment]
> 

This worked, I was reasonably sure I did this though 😂

**Comment by shivammathur** [comment]
@adampatterson 

Please run
```
brew reinstall memcached@8.1
```

Then check for ini files for PHP 8.1 in `$(brew --prefix)/etc/php/8.1/conf.d` directory.
it should show `20-igbinary.ini`, `20-msgpack.ini`, and `30-memcached.ini`.
If you have a `20-memcached.ini` or a `memcached.ini`, please delete those.

same for other versions if you have them installed.

**Comment by adampatterson** [comment]
@shivammathur  It's working now! My error was not restarting FPM but only restarting NGINX.

Thanks for the help and quick reply!
