### ISSUE TITLE
MongoDB extension error with icu4c

### ISSUE THREAD

**Issue by jdecool** [shivammathur/homebrew-extensions#2015]
**Describe the bug**

Like what happens in https://github.com/shivammathur/homebrew-php/issues/1068, (at least) the MongoDB extension is broken

```
Library not loaded: '/opt/homebrew/opt/icu4c/lib/libicuuc.70.dylib'
  Referenced from: '/opt/homebrew/Cellar/mongodb@7.4/1.14.0/mongodb.so'
  Reason: tried: '/opt/homebrew/opt/icu4c/lib/libicuuc.70.dylib' (no such file)
```

**PHP versions**

7.3 7.4 8.0 8.1 and maybe more

**Are you willing to submit a PR?**

I don't think so

**Comment by shivammathur** [comment]
I have rebuilt it with `icu4c 71.1`.

Please update the tap and reinstall the extension

For example, for PHP 8.0
```zsh
brew update
brew reinstall shivammathur/extensions/mongodb@8.0
```

**Comment by jdecool** [comment]
Thanks for your reactivity and your awesome work !
