### ISSUE TITLE
Add sqlsrv and pdo_sqlsrv extensions

### ISSUE THREAD

**Issue by stevdompl** [shivammathur/homebrew-extensions#2032]
Thank you for your tap!

**Describe the feature**
Could you please add the [sqlsrv](https://pecl.php.net/package/sqlsrv) and [pdo_sqlsrv](https://pecl.php.net/package/pdo_sqlsrv) extensions?

**Additional context**
https://github.com/microsoft/msphpsql
https://docs.microsoft.com/pl-pl/sql/connect/php/microsoft-php-driver-for-sql-server
https://docs.microsoft.com/pl-pl/sql/connect/odbc/microsoft-odbc-driver-for-sql-server

**Comment by shivammathur** [comment]
Added
