### ISSUE TITLE
Redis Extension redis@8.2 installation Failed

### ISSUE THREAD

**Issue by nmfirdausw** [shivammathur/homebrew-extensions#2435]
### Below is error when I try to install redis extention for php8.2

Error: redis@8.2: Failed to download resource "igbinary@8.2"
Download failed: https://github.com/shivammathur/homebrew-extensions/releases/download/igbinary@8.2-3.2.12/igbinary%408.2-3.2.12.arm64_monterey.bottle.1.tar.gz

**Comment by shivammathur** [comment]
Please run `brew update`. That should fix it.

**Comment by nmfirdausw** [comment]
Thanks
