### ISSUE TITLE
Add ext-opentelemetry

### ISSUE THREAD

**Issue by xvilo** [shivammathur/homebrew-extensions#2670]
**Describe the feature**
The PHP OpenTelemetry has been very busy creating the first 1.0 releases of the runtime SDK and auto instrumentation together with the `opentelemetry` extension. It has been published on PECL since yesterday. 

It would be great if we can start providing this extension from this tap.

**Additional context**
- PECL: https://pecl.php.net/package/opentelemetry
- Extension Source: https://github.com/open-telemetry/opentelemetry-php-instrumentation 

**Are you willing to submit a PR?**
Possibly yes, but right now no.

**Comment by siketyan** [comment]
@shivammathur @xvilo Can we close this since #3580 was merged?
