### ISSUE TITLE
redis@8.2 does not create the so/ini files

### ISSUE THREAD

**Issue by necmettin** [shivammathur/homebrew-extensions#2673]
**Describe the bug**
after `brew install shivammathur/extensions/redis@8.2`, a `/usr/local/etc/php/8.2/conf.d/20-redis.ini` should be created in the system, but `The post-install step did not complete successfully`

**PHP versions**
8.2.4 from shivammathur/php

**To Reproduce**
```
brew tap shivammathur/php
brew tap shivammathur/extensions
brew install shivammathur/php/php@8.2
brew install shivammathur/extensions/redis@8.2
```

**Expected behavior**
`php -m` should list redis as an installed module

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**
I'm not really proficient with installing a PHP module in MacOS (or Ruby for that matter - I couldn't even find the post-install step in the Ruby file).

**Comment by shivammathur** [comment]
Please run `brew doctor` and fix any issues it reports, and then try again.

**Comment by necmettin** [comment]
> Please run `brew doctor` and fix any issues it reports, and then try again.

Had already done that, forgot to mention. Just did it again, no problems there. Anything else I can do to find the issue?

**Comment by shivammathur** [comment]
@necmettin 
ok.

Try running the postinstall step with debug now and provide me the logs
```zsh
brew postinstall --debug redis@8.2
```

**Comment by necmettin** [comment]
Hello again,

After the command you gave, although `brew doctor` was not reporting any errors, postinstall was reporting `unable to write`, so I uninstalled homebrew, removed all artifacts and reinstalled homebrew and shivammathur/php@8.2, shivammuthar/extensions/redis@8.2 is now reported as installed when I `php -m`. So it was a permission issue after all. Thank you very much.
