### ISSUE TITLE
trying to install zmq extension with no success.. can you please help?

### ISSUE THREAD

**Issue by george-gl** [shivammathur/homebrew-extensions#270]

**Comment by shivammathur** [comment]
Please let me know your OS version and what you tried.

**Comment by george-gl** [comment]
mac os on the m1 processor. 
I installed php using `brew install shivammathur/php/php@7.3` and then for the extensions I used  `brew tap shivammathur/extensions` and in this case `brew install zmq@7.3` and `brew install shivammathur/extensions/zmq@7.3` 

thank you

**Comment by shivammathur** [comment]
ok, `zmq` is not in this tap. I will add it.

**Comment by george-gl** [comment]
thank you! I appreciate

**Comment by shivammathur** [comment]
@george-gl Added `zmq`.

- Please update the tap before installing
```
brew update
```

- Install `zmq`
```
brew install shivammathur/extensions/zmq@7.3
```

**Comment by george-gl** [comment]
cheers mate! I appreciate! works like a charm 👍
