### ISSUE TITLE
Memcache 8.2

### ISSUE THREAD

**Issue by xepozz** [shivammathur/homebrew-extensions#2730]
Memcache extension was released yesterday.
https://pecl.php.net/package/memcache

I don't know Ruby, but now default version is 8.0
https://github.com/shivammathur/homebrew-extensions/blob/master/Formula/memcache%408.2.rb#L11

Could you add the newest version or tell me what I need to do to upgrade?

**Comment by shivammathur** [comment]
@xepozz 

Updated

**Comment by xepozz** [comment]
Thanks a lot

**Comment by shivammathur** [comment]
@xepozz Please create an issue with the details about your workflow [here](https://github.com/shivammathur/setup-php/issues)
