### ISSUE TITLE
Add Support for Phalcon 5 on PHP 8.2

### ISSUE THREAD

**Issue by wielorzeczownik** [shivammathur/homebrew-extensions#2992]
**Describe the feature**
Add support for Phalcon 5 on PHP 8.2.

**Additional context**
Phalcon version 5.2.3 is available as an extension in PECL for PHP version 8.2

- PECL: https://pecl.php.net/package/phalcon/5.2.3

**Are you willing to submit a PR?**
Maybe in the future.

**Comment by shivammathur** [comment]
Added in https://github.com/shivammathur/homebrew-extensions/pull/2993
