### ISSUE TITLE
Error: Possible conflicting files are: /usr/local/include/php/ext/imap/php_imap.h -> /usr/local/Cellar/imap@7.1/7.1.33/include/php/ext/imap/php_imap.h

### ISSUE THREAD

**Issue by OskarStark** [shivammathur/homebrew-extensions#33]
**Describe the bug**
Error when using the following script:
```
The formula built, but is not symlinked into /usr/local
Could not symlink include/php/ext/imap/php_imap.h
Target /usr/local/include/php/ext/imap/php_imap.h
is a symlink belonging to imap@7.1. You can unlink it:
  brew unlink imap@7.1

To force the link and overwrite all conflicting files:
  brew link --overwrite imap@7.4

To list all files that would be deleted:
  brew link --overwrite --dry-run imap@7.4

Possible conflicting files are:
/usr/local/include/php/ext/imap/php_imap.h -> /usr/local/Cellar/imap@7.1/7.1.33/include/php/ext/imap/php_imap.h
```
**PHP versions**
5.6 -> 8.1

**To Reproduce**
The script:
```bash
#!/bin/bash

# This is based on:
# * https://github.com/shivammathur/homebrew-php
# * https://github.com/shivammathur/homebrew-extensions

PHP_VERSIONS="5.6 7.0 7.1 7.2 7.3 7.4 8.0 8.1"
EXTENSIONS="amqp imagick imap pcov"

echo "Add taps"
brew tap shivammathur/php
brew tap shivammathur/extensions

echo "Remove all available PHP configs"
rm -rf /usr/local/etc/php/*

for version in $PHP_VERSIONS
do
    echo "Install PHP $version with: $EXTENSIONS"

    brew reinstall shivammathur/php/php@$version
    brew link --overwrite --force php@$version

    for extension in $EXTENSIONS
    do
        echo "Extension: $extension"
        brew reinstall shivammathur/extensions/$extension@$version
    done

    php -v
    for extension in $EXTENSIONS
    do
        php -m | grep $extension
    done
done
```

**Expected behavior**
No error

**Screenshots/Logs**
![CleanShot 2021-01-11 at 14 13 02](https://user-images.githubusercontent.com/995707/104186787-38459f80-5417-11eb-84bb-72e452dc5cf2.png)

**Comment by shivammathur** [comment]
@OskarStark try unlinking and linking again

```
brew unlink imap@7.1
brew link --force --overwrite imap@7.1
```

**Comment by shivammathur** [comment]
@OskarStark I pushed an update, please fetch the tap again and test.

**Comment by OskarStark** [comment]
Hmm unfortunately not 😢 

![CleanShot 2021-01-11 at 16 27 11](https://user-images.githubusercontent.com/995707/104201453-1275c600-542a-11eb-9f34-00a1a529d639.png)

![CleanShot 2021-01-11 at 16 27 17](https://user-images.githubusercontent.com/995707/104201462-14d82000-542a-11eb-88fc-5d3507a7155d.png)

![CleanShot 2021-01-11 at 16 27 52](https://user-images.githubusercontent.com/995707/104201470-16a1e380-542a-11eb-99da-a0b818a5edea.png)

![CleanShot 2021-01-11 at 16 28 28](https://user-images.githubusercontent.com/995707/104201474-17d31080-542a-11eb-8971-52a55c021821.png)

How can I ensure I use the latest tap?

**Comment by shivammathur** [comment]
My ci was broken, rebuilding again after change.

**Comment by shivammathur** [comment]
@OskarStark Try now.

To get the latest tap, untap and tap again.

```zsh
HOMEBREW_DEVELOPER=1 brew untap shivammathur/extensions
brew tap shivammathur/extensions
```

**Comment by OskarStark** [comment]
Looks like its working, thank you very much!
