### ISSUE TITLE
How do I specify an extended version？

### ISSUE THREAD

**Issue by SmallEasy** [shivammathur/homebrew-extensions#3484]
I'm through the brew install shivammathur/PHP/php@8.0 PHP8 installed, and then through the brew install shivammathur/extensions/swoole@8.0 installation swoole extensions

At present, I need php8 to expand the version of swoole 4.8.11, not 5.1.0, how to specify the extension version，

![image](https://github.com/shivammathur/homebrew-extensions/assets/27684352/55d3d266-4a14-4e7f-810b-55b22b894896)

I found that the swoole version of php7.2 is just 4.8.11. After copying the content of Formula/swoole@7.2.rb to Formula/swoole@8.0.rb, I realized the function that I needed to specify the version. But once I or the system automatically executed brew upgrade, swoole's version will be automatically upgraded to version 5. How can I avoid this problem? Thank you

![image](https://github.com/shivammathur/homebrew-extensions/assets/27684352/d8c57baa-9de1-4afe-a3db-3c97aab2d10d)

I also tried to copy php7.2 swoole.so directly into php8's swoole@8.0.brew directory, but php --ri swoole displays Extension 'swoole' not present.

**Comment by SmallEasy** [comment]
I will copy the contents of swoole@7.2.rb to swoole@8.0.rb, and then execute the brew reinstall -s shivammathur/extensions/swoole@8.0, after the success of the execution, and then execute PHP - ri swoole, I found that swoole version has been successfully changed to swoole@7.2.rb version. At present, I can only temporarily solve my demands through this method, but it still cannot solve the automatic upgrade problem caused by brew upgrade

**Comment by shivammathur** [comment]
You can use `brew pin` to solve this
https://docs.brew.sh/FAQ#how-do-i-stop-certain-formulae-from-being-updated

But the better way is to fork the project and maintain your own tap, since this tap is updated when a new version is released for an extension, by default it will be updated on your end when you run `brew upgrade`.

**Comment by SmallEasy** [comment]
I use After the brew pin shivammathur/extensions/swoole@8.0, 
and then execute The brew upgrade shivammathur/extensions/swoole@8.0, found swoole versions have been fixed down, thank you!

![image](https://github.com/shivammathur/homebrew-extensions/assets/27684352/a18105a8-0b61-407a-8d42-25db89abc849)


However, this is certainly not the final optimal solution, so I hope to be able to support the installation of the specified version, thank you
