### ISSUE TITLE
ext-redis

### ISSUE THREAD

**Issue by OskarStark** [shivammathur/homebrew-extensions#358]
**Describe the feature**
Add extension `redis`

**Additional context**
I would love to have redis extension in your homebred-extensions repo 😍 

Thanks

**Comment by shivammathur** [comment]
Added

**Comment by OskarStark** [comment]
Thank you very much!

**Comment by OskarStark** [comment]
Works well so far except a warning:
```
PHP Warning:  Cannot load module "redis" because required module "igbinary" is not loaded in Unknown on line 0

Warning: Cannot load module "redis" because required module "igbinary" is not loaded in Unknown on line 0
```

any clue? 🤔

**Comment by OskarStark** [comment]
friendly ping @shivammathur 🙏

**Comment by shivammathur** [comment]
@OskarStark 
Sorry for the delay, I did not notice your comment in my notifications.

In my testing (https://github.com/shivammathur/test-setup-php/actions/runs/588695225/workflow), the tap is working correctly. 
Igbinary is a dependency of redis in each redis formulae, so it should be installed before redis is installed.

Fetch the tap again, then remove igbinary and redis if installed previously, and then install redis again.
```zsh
# Update tap
HOMEBREW_DEVELOPER=1 brew untap shivammathur/extensions
brew tap shivammathur/extensions

# Adjust php versions as per your requirements.
for php_version in 7.2 7.3 7.4; do
   brew remove igbinary@$php_version || true
   brew remove redis@$php_version || true

   brew install redis@$php_version
done
``

**Comment by OskarStark** [comment]
Will try, thanks

**Comment by OskarStark** [comment]
Hmm, this looks weird:
![CleanShot 2021-02-22 at 11 52 49](https://user-images.githubusercontent.com/995707/108698553-8a90da80-7504-11eb-8481-edea44d6c06c.png)

This is my script: https://gist.github.com/OskarStark/93e79e2faca261530762d116c7ebf2a4

**Comment by shivammathur** [comment]
@OskarStark 
Yes, first remove `redis` then `igbinary`.

```zsh
if [ "$extension" = "redis" ]; then
    brew remove redis@$version || true
    brew remove igbinary@$version || true
fi
```

**Comment by OskarStark** [comment]
Now the same error with:
```
~/dev/OskarStark/dotfiles/homebrew • php -v                                                                                                                                                                                              12:15
PHP Warning:  Cannot load module "redis" because required module "msgpack" is not loaded in Unknown on line 0

Warning: Cannot load module "redis" because required module "msgpack" is not loaded in Unknown on line 0
PHP 8.0.2 (cli) (built: Feb  4 2021 18:10:29) ( NTS )
Copyright (c) The PHP Group
```

I try to remove it too

**Comment by OskarStark** [comment]
yep, now it works 👍 👍 
```bash
        if [ "$extension" = "redis" ]; then
            brew remove redis@$version || true
            brew remove igbinary@$version || true
            brew remove msgpack@$version || true
        fi
```
