### ISSUE TITLE
How do I install a version of a given extension

### ISSUE THREAD

**Issue by 1372143376** [shivammathur/homebrew-extensions#3693]
```

brew install shivammathur/extensions/redis@7.4

The default redis extension installed is version 6.X
```
The version I want to install redis extension is 4.X

**Comment by shivammathur** [comment]
There is no direct way to do this.

You can fork the repo, edit the formula for the older version, and build from the source.
You have to edit the `url` and the `sha256` hash in the formula and then you can build from the source. But for redis 4.x, you will have to change the configure `opts` as well. Refer to the options in `config.m4` file for the version.
```zsh
brew install -s <formula_name>
```
