### ISSUE TITLE
Warning with PHP 8.2 and 8.3 if IMAP extension module is installed

### ISSUE THREAD

**Issue by InvisibleSmiley** [shivammathur/homebrew-extensions#3774]
When you install php@8.2 with imap@8.2 or php@8.3 with imap@8.3 you get the following (twice) with `php -v`:

```
Warning: Module "imap" is already loaded in Unknown on line 0
```

The problem does not exist with php@8.1 and imap@8.1.

**PHP versions**
8.2 and 8.3

**To Reproduce**
1. Install the above mentioned package combinations
2. Run `php -v`

**Expected behavior**
No warnings

**Additional context**
- There is a 20-imap.ini for all three PHP versions under /opt/homebrew/etc/php/<version>/conf.d
- Compare `php -i` compile options between php@8.1, php@8.2 and php@8.3. You will see that IMAP is compiled into PHP itself for versions 8.2 and 8.3 but not 8.1.

**Are you willing to submit a PR?**
No

**Comment by shivammathur** [comment]
Please install PHP from shivammathur/php tap in case you want to install imap extension using this tap.
