### ISSUE TITLE
pecl_http@8.3 icu4c version error 

### ISSUE THREAD

**Issue by HapiCZ** [shivammathur/homebrew-extensions#3795]
**Describe the bug**
If pecl_http is endabled php throwing erro:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/homebrew/opt/pecl_http@8.3/http.so' (tried: /opt/homebrew/opt/pecl_http@8.3/http.so (dlopen(/opt/homebrew/opt/pecl_http@8.3/http.so, 0x0009): Library not loaded: /opt/homebrew/opt/icu4c/lib/libicui18n.73.dylib
  Referenced from: <25749073-7EF8-3A72-9EC0-B9ECD1AB2E7A> /opt/homebrew/Cellar/pecl_http@8.3/4.2.4/http.so
  Reason: tried: '/opt/homebrew/opt/icu4c/lib/libicui18n.73.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/icu4c/lib/libicui18n.73.dylib' (no such file), '/opt/homebrew/opt/icu4c/lib/libicui18n.73.dylib' (no such file), '/opt/homebrew/Cellar/icu4c/74.2/lib/libicui18n.73.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/icu4c/74.2/lib/libicui18n.73.dylib' (no such file), '/opt/homebrew/Cellar/icu4c/74.2/lib/libicui18n.73.dylib' (no such file)), /opt/homebrew/lib/php/pecl/20230831//opt/homebrew/opt/pecl_http@8.3/http.so.so (dlopen(/opt/homebrew/lib/php/pecl/20230831//opt/homebrew/opt/pecl_http@8.3/http.so.so, 0x0009): tried: '/opt/homebrew/lib/php/pecl/20230831//opt/homebrew/opt/pecl_http@8.3/http.so.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/php/pecl/20230831//opt/homebrew/opt/pecl_http@8.3/http.so.so' (no such file), '/opt/homebrew/lib/php/pecl/20230831//opt/homebrew/opt/pecl_http@8.3/http.so.so' (no such file))) in Unknown on line 0
`

**PHP versions**
PHP 8.3 

**To Reproduce**
1. install php@8.3
2. install pecl_http@8.3 
3 run php -v 

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
I have added new builds to fix this. Will update once they are completed.

**Comment by HapiCZ** [comment]
good job. thank you

**Comment by shivammathur** [comment]
It should work now

```
brew update
brew reinstall shivammathur/extensions/pecl_http@8.3
```
