### ISSUE TITLE
Unable to load redis on php8.1

### ISSUE THREAD

**Issue by deZinc** [shivammathur/homebrew-extensions#3796]
**Describe the bug**
I had a working version of many php's on my laptop. After a single extension update which triggered a large brew upgrade, I started having issues. I found them described in the issue list here and indeed, a new reinstall of the php fixed them except for php 8.1 where I still get an error with redis.

Tried a lot of things that I found on the internet such as these 2, but did not manage to get it fixed:
https://github.com/phpredis/phpredis/issues/2056

**PHP versions**
8.1

**To Reproduce**
 brew install shivammathur/extensions/redis@8.1

**Expected behavior**
A smooth running redis after the install. :)

**Screenshots/Logs**

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/redis@8.1/redis.so' (tried: /usr/local/opt/redis@8.1/redis.so (dlopen(/usr/local/opt/redis@8.1/redis.so, 0x0009): symbol not found in flat namespace '_php_msgpack_serialize'), /usr/local/lib/php/pecl/20210902//usr/local/opt/redis@8.1/redis.so.so (dlopen(/usr/local/lib/php/pecl/20210902//usr/local/opt/redis@8.1/redis.so.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210902//usr/local/opt/redis@8.1/redis.so.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/php/pecl/20210902//usr/local/opt/redis@8.1/redis.so.so' (no such file), '/usr/local/lib/php/pecl/20210902//usr/local/opt/redis@8.1/redis.so.so' (no such file))) in Unknown on line 0

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
Please update the tap and reinstall redis@8.1

```
brew update
brew reinstall shivammathur/extensions/redis@8.1
```
