### ISSUE TITLE
ldap extension for php 7.4.x

### ISSUE THREAD

**Issue by guescinr** [shivammathur/homebrew-extensions#3923]
**Describe the feature**

Are there any plans of adding php-ldap to extensions?

**Underlying issue**

Installed php@7.4 through brew, but cannot find the ldap-extension
**Describe alternatives**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
@guescinr 

ldap is compiled statically in the php binaries in the brew formula, so it is not required to be installed separately.
https://github.com/shivammathur/homebrew-php/blob/master/Formula/php%407.4.rb#L173

Please run `php -m` to check if the extension is loading on your end.
