### ISSUE TITLE
Xdebug for php 8.4 causes segmentation faults

### ISSUE THREAD

**Issue by lllopo** [shivammathur/homebrew-extensions#4272]
**Describe the bug**
When the Xdebug@8.4 is installed and activated, php-fpm fails with [pool www] child 44737 exited on signal 11 (SIGSEGV)

**PHP versions**
8.4

**To Reproduce**
Install php@8.4 with xdebug@8.4

**Expected behavior**
Works

**Screenshots/Logs**

**Additional context**
It seems to me that the Xdebug version is 3.3.0, which is not compatible with PHP 8.4, has to be 3.4.0

**Are you willing to submit a PR?**
No

**Comment by shivammathur** [comment]
Updated
