### ISSUE TITLE
Clean up deprecated warnings about implicit versus explicit nullables with PHP 8.4

### ISSUE THREAD

**Issue by craigconstantine** [shivammathur/homebrew-extensions#4498]
Possibly not an exhaustive list of places, but these are ones I'm seeing in my little application…

PHP Deprecated:  PhpImap\Mailbox::__construct(): Implicitly marking parameter $attachmentsDir as nullable is deprecated, the explicit nullable type must be used instead in [redacted]/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 168

PHP Deprecated:  PhpImap\Mailbox::setConnectionArgs(): Implicitly marking parameter $params as nullable is deprecated, the explicit nullable type must be used instead in [redacted]/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 383

PHP Deprecated:  PhpImap\Mailbox::sortMails(): Implicitly marking parameter $charset as nullable is deprecated, the explicit nullable type must be used instead in [redacted]/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 1020

PHP Deprecated:  PhpImap\Mailbox::appendMessageToMailbox(): Implicitly marking parameter $internal_date as nullable is deprecated, the explicit nullable type must be used instead in [redacted]/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 1634

PHP Deprecated:  PhpImap\Imap::append(): Implicitly marking parameter $options as nullable is deprecated, the explicit nullable type must be used instead in [redacted]/vendor/php-imap/php-imap/src/PhpImap/Imap.php on line 78

PHP Deprecated:  PhpImap\Imap::search(): Implicitly marking parameter $charset as nullable is deprecated, the explicit nullable type must be used instead in [redacted]/vendor/php-imap/php-imap/src/PhpImap/Imap.php on line 818

PHP Deprecated:  PhpImap\Imap::sort(): Implicitly marking parameter $search_criteria as nullable is deprecated, the explicit nullable type must be used instead in [redacted]/vendor/php-imap/php-imap/src/PhpImap/Imap.php on line 904

**Comment by shivammathur** [comment]
@craigconstantine This is not a PHP 8.4 issue, php-imap needs to be updated to support it. Please see https://github.com/barbushin/php-imap/pull/722
