### ISSUE TITLE
Add mcrypt

### ISSUE THREAD

**Issue by maganius** [shivammathur/homebrew-extensions#698]
Thanks for this awesome tap! It would be great if you could add the mcrypt (php 5.6) extension.

**Comment by shivammathur** [comment]
On PHP5.6, mcrypt should be available by default in [shivammathur/php](https://github.com/shivammathur/homebrew-php) tap
Test: https://github.com/shivammathur/test-setup-php/runs/2380520227?check_suite_focus=true#step:8:29

**Comment by maganius** [comment]
@shivammathur thanks you for your fast reply, how I can install that? or what I need put in php.ini to enable mcrypt?
