### ISSUE TITLE
Imagick version not reported correctly

### ISSUE THREAD

**Issue by morloderex** [shivammathur/homebrew-extensions#926]
Imagick is not reporting the extension version correctly.

**PHP versions**
Every php versions effected

**To Reproduce**
Just install any of the imagick@* formula and execute a command like `php -m or phpinfo();` in a script

You will see `imagick module version` reported as `@PACKAGE_VERSION@`

**Expected behavior**
You will see `imagick module version` to be correctly reported as the given release number.

**Additional context**
If you go to [this link](https://github.com/Imagick/imagick/blob/master/php_imagick.h#L26-L29) you see the comment specifically states that the version is only being populated by builds comming from the official pecl site.

It may be that when installing imagick for any php version that has not yet been released we should still build it from the github source sence that returns the latest code and might be able to compile better than a released version.

Given that imagick version 3.5.0 has been released officially which includes php 8.0 support officially it should be possible to use that version now instead of the build from github source.

Also looking at the Changelog for imagick 3.4.4 it looks like we can hardcode the version to 3.4.4 for imagick if using a php version < 7.x otherwise we should be good to go with version 3.5.0 for time being.

**Are you willing to submit a PR?**
I am not familiar with the project i just wanted to come in and say that this seems like a bug in the packaging of imagick.

**Comment by shivammathur** [comment]
@morloderex Switched to `PECL` for `imagick`. Builds are in progress, should finish in an hour.

**Comment by morloderex** [comment]
@shivammathur Saw the commit but you might need to revert to 3.4.4 for builds below 7.x.

**Comment by shivammathur** [comment]
@morloderex Not as per the package.xml in `imagick` https://github.com/Imagick/imagick/blob/6fb660ec492834a546c7cc383a29ea3ce5b5cf17/package.xml#L417

Is there a known issue regarding this?

**Comment by morloderex** [comment]
I dont really know the changelog on pecl for 3.4.4 states something else than the package.xml.

So i am not entirely sure what's up and down here.

Let's go with 3.5.0 for now and see if any reports of issues comes in we can revert to 3.4.4 by then.

**Comment by shivammathur** [comment]
@morloderex All builds are complete. It should now show the version correctly. So, please update the tap and reinstall.
