### ISSUE TITLE
Imap & Spatie/Ray causes Apache segmentation fault

### ISSUE THREAD

**Issue by mxrxdxn** [shivammathur/homebrew-extensions#927]
**Describe the bug**
imap & spatie/ray causes Apache segmentation fault

**PHP versions**
8.0.7, 7.4.20, 7.3.28

**To Reproduce**
Install the imap extension, then add spatie/ray to a project and call the function `ray('test');`.

**Expected behavior**
Ray output is sent to the Ray app and normal HTML content is sent back to the browser.

**Screenshots/Logs**
![error](https://camo.githubusercontent.com/481a8cd772b3df506831715e5128c7c01eb8881dff0826f25e139d47e11f1cd7/68747470733a2f2f7032382e70302e6e302e63646e2e676574636c6f75646170702e636f6d2f6974656d732f324e75716d796b512f66383536623965612d333731612d343063652d616665342d3131363537643464343530302e706e67)

**Additional context*
I initially raised this as an issuee in the spatie/ray repository however I believe it to not be at fault; disabling imap restores all functionality again.

**Are you willing to submit a PR?**
If I can figure out how to fix it!

**Comment by shivammathur** [comment]
I could not reproduce the issue. (See attached screenshot).
Please provide apache logs related to the crash to `spatie/ray` maintainers.

![macos](https://user-images.githubusercontent.com/1571086/123813840-d91b0f00-d912-11eb-89e6-e6e1f99c6f2e.png)
