### ISSUE TITLE
Add mongodb

### ISSUE THREAD

**Issue by wtry** [shivammathur/homebrew-extensions#954]
Thanks for this awesome tap! It would be great if you could add the mongodb extension.

tap php has shivammathur/php/php

if you could add the shivammathur/extensions/swoole
if you could add the shivammathur/extensions/redis

**Comment by shivammathur** [comment]
@wtry Added in https://github.com/shivammathur/homebrew-extensions/commit/4e75b90da6113ce6e703658269c70b35816d7e87
